[package]
name = "kpepe-jackpot"
version = "1.0.0"
edition = "2021"
authors = ["KPEPE Team"]

[lib]
path = "src/lib.rs"

[dependencies]
klever-sc = "0.45.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
